### ISSUE TITLE
Troubles Uploading after First Upload

### ISSUE THREAD

**Issue by Dracrius** [nnguy132/Switch-Frame-Advancer#2]
Sorry I know I just closed one issue but now I can't figure out how to upload it to me Arduino Micro. I was able to follow all the steps up until here
`
Once finished building, start up Arduino IDE. Under File -> Preferences, check Show verbose output during: upload and pick OK. With the Arduino plugged in and properly selected under Tools, upload any sketch. Find the line with avrdude and copy the entire avrdude command and all options into a terminal, replacing the .hex file and path to the location of the Joystick.hex created in the previous step. Also make sure the -P/dev/?? port is the same as what Arduino IDE is currently reporting. Now double tap the reset button on the Arduino and quickly press Enter in the terminal. This may take several tries. You may need to press Enter first and then the reset button or try various timings. Eventually, avrdude should report success.`

There is no reset button on my arduino micro so I can not do what they ask. I tried unpluging and repluging it in quickly but i had no luck it just says 
```D:\Switch-Frame-Advancer>C:\Users\Dracrius\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.3.0-arduino17/bin/avrdude -CC:\Users\Dracrius\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.3.0-arduino17/etc/avrdude.conf -v -patmega32u4 -cavr109 -PCOM6 -b57600 -D -Uflash:w:D:\Switch-Frame-Advancer\Joystick.hex:i

avrdude: Version 6.3-20190619
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2014 Joerg Wunsch

         System wide configuration file is "C:\Users\Dracrius\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.3.0-arduino17/etc/avrdude.conf"

         Using Port                    : COM6
         Using Programmer              : avr109
         Overriding Baud Rate          : 57600
avrdude: ser_open(): can't open device "\\.\COM6": The system cannot find the file specified.


avrdude done.  Thank you.
```

Is this how you upload?

**Comment by Dracrius** [comment]
proper instructions for a Arduino Micro

-Momentarily connect a jumper wire between the RST and GND pins on your Pro Micro
-Immediately press the "Enter" key on your keyboard to run the avrdude commmand you pasted to the Windows  command line.

**Comment by Dracrius** [comment]
Mhh question how do I upload a new version to my arduino once i have flashed it once. It doesnt show in windows after the first upload which I guess makes sense its probably trying to run the macro but I have no idea how I will change the shiny frame value.

**Comment by nnguy132** [comment]
I dont have experience with the micro but to upload again it would likely just be connecting the jumper cable again b4 flashing again

**Comment by Dracrius** [comment]
Thanks for all the help
