### ISSUE TITLE
fatal error. can't create obj/joystick o

### ISSUE THREAD

**Issue by guccixsteve** [nnguy132/Switch-Frame-Advancer#3]
while running the make command I've gotten this error that won't let me make the hex files. not sure whats wrong. lufa is installed, and so is winavr. pretty sure i did everything. 
Microsoft Windows [Version 10.0.18362.592]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\senic\Desktop\teensy projects\Switch-Frame-Advancer-master>make
      0 [main] sh 9420 sync_with_child: child 8692(0x184) died before initialization with status code 0xC0000142
    241 [main] sh 9420 sync_with_child: *** child state waiting for longjmp
/usr/bin/sh: fork: Resource temporarily unavailable
      0 [main] sh 18148 sync_with_child: child 20896(0x1D8) died before initialization with status code 0xC0000142
    219 [main] sh 18148 sync_with_child: *** child state waiting for longjmp
/usr/bin/sh: fork: Resource temporarily unavailable
      0 [main] sh 18848 sync_with_child: child 19696(0x1D8) died before initialization with status code 0xC0000142
    198 [main] sh 18848 sync_with_child: *** child state waiting for longjmp
/usr/bin/sh: fork: Resource temporarily unavailable
 [INFO]    : Begin compilation of project "Joystick"...

avr-gcc (WinAVR 20100110) 4.3.3
Copyright (C) 2008 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 [GCC]     : Compiling C file "Joystick.c"
avr-gcc -c -pipe -gdwarf-2 -g2 -mmcu=atmega32u4 -fshort-enums -fno-inline-small-functions -fpack-struct -Wall -fno-strict-aliasing -funsigned-char -funsigned-bitfields -ffunction-sections -I. -DARCH=ARCH_AVR8 -DF_CPU=16000000UL -mrelax -fno-jump-tables -x c -Os -std=gnu99 -Wstrict-prototypes -DUSE_LUFA_CONFIG_HEADER -IConfig/  -I. -ILUFA/LUFA/.. -DARCH=ARCH_AVR8 -DBOARD=BOARD_NONE -DF_USB=16000000UL  -MMD -MP -MF obj/Joystick.d Joystick.c -o obj/Joystick.o
Assembler messages:
Fatal error: can't create obj/Joystick.o: No such file or directory

**Comment by nnguy132** [comment]
Id very much recommend not using winAVR. Id follow this guide to install the avr toolkit, avrdude and GNUwin32
http://fab.cba.mit.edu/classes/863.16/doc/projects/ftsmin/windows_avr.html

Then use gitbash or something to run the make file

**Comment by guccixsteve** [comment]
alright. where exactly can i find the link for the AVRtoolchain? the site linked in the guide seems to be broken. there's no download for the avr installer
edit: your tutorial worked. i got the toolchain from [here](https://www.microchip.com/mplab/avr-support/avr-and-arm-toolchains-c-compilers) i renamed the folder in the archive to avr8-gnu-toolchain and extracted it to program files. then i edited my path and ran the make command in gitbash

**Comment by guccixsteve** [comment]
so after making the joystick.hex and trying to flash it to my teensy 2.0 ++ it said that the code isn't compiled for this board. is there any way for me to convert it to the correct board

**Comment by nnguy132** [comment]
Change the MCU in the makefile to the appropriate microcontroller

https://www.pjrc.com/teensy/index.html

No guarantee that it works on teensy++ 2.0 though.

**Comment by guccixsteve** [comment]
Yep. Working fine, thank you. Also, is it fine that it changes the month? Or should I change the code to apply to days instead

**Comment by nnguy132** [comment]
Should be fine for months, you can however change for days instead if youd like
